# 对话设置
conversation_setting:

  system: "现在你是一位旅行规划助手，你的名字叫nishuone028，你的说话方式是温柔、热情、熟练各种地方的景点及其历史渊源、称呼游客为[小伙伴]。你能够根据用户提出的地点给出对应的旅游方案并且解答用户提出的疑问。"
  first_input: "我的{attraction_info}，你需要根据我给出的景点信息撰写一段景点旅游规划。你需要放大景点的亮点价值，激发游客的旅游欲望。"


# 数据集生成设置
data_generation_setting:

  # 每个景点生成 ${each_tour_gen} 个 conversion 数据，conversion 中包含【景点介绍 + QA】，
  each_tour_gen: 3

  # 每个 conversion 中的的对话数，文案为 1 个，其余会生成 ${each_conversation_qa} - 1 个 QA
  each_conversation_qa: 5

  # 每个景点生成随机抽取 ${each_pick_highlight} 个亮点
  each_pick_highlight: 3

  # 每个景点生成后随机抽取 ${each_pick_question} 个问题生成游客的提问
  each_pick_question: 3

  # 数据集生成 prompt
  dataset_gen_prompt: 现在你是一位旅行规划助手，你的名字叫{role_type}，你的说话方式是{character}。
                      我的{attraction_info}，你需要根据我给出的景点信息撰写一段至少100字的景点旅游规划。你需要放大景点的亮点价值，激发游客的旅游欲望。
                      输出旅游规划后，结合景点信息站在游客的角度根据[{customer_question}]提出{each_conversation_qa}个问题并解答。
                      全部输出的信息使用我期望的 json 格式进行输出：{dataset_json_format}。注意 json 一定要合法。

  # 数据生成 json 格式
  dataset_json_format:
    '{
      "conversation": [
        {
          "output": 景点介绍文案，格式化一行输出，不要换行。
        },
        {
          "input": 游客的问题,
          "output": 主播回答
        },
        {
          "input": 游客的问题,
          "output": 主播回答
        },
        ... 直到问题结束
      ]
    }'

# 说明书生成设置
instruction_generation_setting:
  # 景点详细说明生成 prompt
  dataset_gen_prompt: 我上传的是一个景点的详细说明，请帮我生成 markdwon 格式的景点描述，需要包含景点名字、景点细节详情、人文历史、亮点，越详细越好，只输出景点描述即可。


# 角色及其性格
role_type:
  nishuone: # 导游
    - 温柔
    - 热情
    - 熟练各种地方的景点及其历史渊源
    - 称呼游客为[小伙伴]

# 景点信息结构体
attraction_info_struct:
  - 景点名是[{name}]，
  - 景点的亮点是[{highlights}]

# prompt: 旅游景点的时候，客户常会问题的问题，举例10个, 只列举大类就行
customer_question_type:
  -景点门票与优惠政策
  -游玩项目与体验
  -开放时间与季节性活动
  -交通路线与停车
  -餐饮与住宿
  -景点安全与设施
  -导游服务与讲解
  -周边游玩与购物
  -环境保护与卫生
  -游客评价与推荐

# 第一个 prompt: 帮我列举10种省份，并每种举例5个城市
# 每个类 prompt: 现在你精通任何地方景点，你可以帮我举例上述城市中的5个景点，以及每个景点的6个亮点或特点，然后用python dict形式输出：{类名：[特点1, 特点2] ...} ，去掉特点12的字样，除python字典外的其他都不要输出，不要有任何的警告信息。 [xxx]
attraction_list:
  广东省:
    广州市:
      广州塔: [ 世界第四高塔, 360度观景台, 夜景灯光秀, 内置旋转餐厅, 空中步道, 动感电影 ]
      长隆欢乐世界: [ 大型主题公园, 过山车, 动物表演, 水上乐园, 儿童乐园, 夜间狂欢 ]
      越秀公园: [ 五羊雕像, 广州博物馆, 城墙遗址, 花卉展览, 风景秀丽, 运动场地 ]
      陈家祠: [ 广东民间工艺博物馆, 精美砖雕, 木雕艺术, 历史文化展, 民俗展示, 古建筑保护 ]
      白云山: [ 自然风景区, 登山步道, 生态动物园, 植物园, 山顶公园, 缆车观光 ]
    深圳市:
      欢乐谷: [ 大型主题公园, 过山车, 水上乐园, 娱乐演出, 儿童游乐区, 夜间狂欢 ]
      华侨城湿地公园: [ 自然保护区, 湿地生态, 野生动物观赏, 环湖步道, 科普教育, 摄影佳地 ]
      深圳湾公园: [ 滨海公园, 环海步道, 自行车道, 海滨景观, 公共艺术, 夜景观赏 ]
      大梅沙海滨公园: [ 沙滩度假, 水上运动, 海滨风景, 休闲娱乐, 海鲜美食, 家庭出游 ]
      莲花山公园: [ 城市公园, 登山步道, 邓小平塑像, 风景秀丽, 休闲活动, 花卉展览 ]
    珠海市:
      珠海长隆海洋王国: [ 大型海洋主题公园, 海洋生物展, 海豚表演, 水上乐园, 娱乐设施, 夜间灯光秀 ]
      圆明新园: [ 仿清代皇家园林, 历史文化展示, 表演活动, 休闲游览, 传统建筑, 文艺演出 ]
      珠海渔女: [ 珠海地标, 海滨雕像, 风景拍摄, 浪漫景点, 游客必访, 文化象征 ]
      外伶仃岛: [ 海岛风光, 沙滩度假, 海上运动, 渔村风情, 海鲜美食, 观光旅游 ]
      珠海博物馆: [ 历史文化展览, 珠海发展史, 文物保护, 教育活动, 临时展览, 互动体验 ]
    佛山市:
      佛山祖庙: [ 历史古刹, 佛教文化, 古建筑群, 文物保护, 民俗展示, 祈福圣地 ]
      南风古灶: [ 陶瓷文化, 历史遗址, 工艺展示, 传统手工艺, 文化体验, 游客互动 ]
      顺德长鹿农庄: [ 农业旅游, 乡村体验, 动物园, 儿童乐园, 生态保护, 休闲娱乐 ]
      梁园: [ 岭南园林, 传统建筑, 花卉展览, 文化活动, 文物保护, 休闲游览 ]
      清晖园: [ 明清古建筑, 园林艺术, 文化遗产, 花卉展示, 历史名胜, 休闲观光 ]
    东莞市:
      松山湖: [ 自然风景区, 环湖步道, 生态保护, 休闲娱乐, 花卉展览, 科普教育 ]
      虎门销烟纪念馆: [ 历史文化展览, 鸦片战争遗址, 爱国教育, 文化活动, 文物保护, 互动体验 ]
      可园: [ 岭南园林, 传统建筑, 花卉展示, 文物保护, 文化活动, 休闲游览 ]
      同沙生态公园: [ 自然风景区, 登山步道, 生态保护, 野生动物, 休闲娱乐, 摄影佳地 ]
      东莞植物园: [ 四季花卉, 生态保护, 科普教育, 家庭休闲, 花卉展览, 观光旅游 ]
  浙江省:
    杭州市:
      西湖: [ 世界遗产, 三潭印月, 苏堤春晓, 雷峰塔, 花港观鱼, 环湖步道 ]
      灵隐寺: [ 千年古刹, 飞来峰石刻, 静谧禅境, 古木参天, 佛教文化, 祈福圣地 ]
      断桥残雪: [ 西湖十景之一, 经典摄影地, 冬季雪景, 白蛇传传说, 浪漫爱情地, 湖滨公园 ]
      宋城: [ 大型文化主题公园, 宋文化表演, 古城风貌, 主题乐园, 美食街, 宋代演出 ]
      杭州植物园: [ 四季花卉, 竹林园, 荷花池, 兰花馆, 生态保护, 科普教育 ]
    宁波市:
      天一阁: [ 中国最古老的私家藏书楼, 文化遗产, 古籍保护, 传统建筑, 文物展览, 文化活动 ]
      东钱湖: [ 自然风景区, 湖泊风光, 休闲娱乐, 游船观光, 水上运动, 度假胜地 ]
      月湖公园: [ 城市公园, 湖泊风景, 古桥古亭, 休闲步道, 花卉展览, 市民活动 ]
      保国寺: [ 千年古刹, 木构建筑, 佛教文化, 历史遗迹, 祈福圣地, 古树名木 ]
      老外滩: [ 历史街区, 中西合璧建筑, 美食街, 文化活动, 江景观光, 夜生活 ]
    温州市:
      雁荡山: [ 世界地质公园, 奇峰怪石, 瀑布景观, 历史文化, 徒步登山, 自然探险 ]
      江心屿: [ 温州名胜, 江中小岛, 古寺古塔, 风景秀丽, 游船观光, 文化活动 ]
      南麂列岛: [ 海岛风光, 海洋保护区, 沙滩度假, 海上运动, 海鲜美食, 生态旅游 ]
      楠溪江: [ 自然风景区, 江河美景, 漂流探险, 古村落, 休闲垂钓, 生态保护 ]
      温州博物馆: [ 历史文化展览, 地方文物, 传统艺术, 教育活动, 临时展览, 互动体验 ]
    嘉兴市:
      南湖: [ 红色旅游, 南湖革命纪念馆, 红船精神, 湖泊风景, 游船观光, 文化活动 ]
      乌镇: [ 江南水乡, 古镇风貌, 传统建筑, 水上表演, 手工艺品, 美食街 ]
      西塘: [ 古镇风貌, 水乡风光, 古桥古巷, 传统文化, 民俗表演, 美食体验 ]
      盐官古镇: [ 古镇风貌, 海宁观潮, 历史建筑, 传统文化, 手工艺品, 美食街 ]
      梅花洲: [ 自然风景区, 花卉展示, 生态保护, 农家乐, 文化活动, 休闲娱乐 ]
    绍兴市:
      鲁迅故里: [ 文学圣地, 鲁迅纪念馆, 鲁迅故居, 文化街区, 传统建筑, 文化活动 ]
      东湖: [ 山水美景, 石灰岩溶洞, 游船观光, 传统园林, 自然探险, 摄影佳地 ]
      兰亭: [ 书法圣地, 王羲之纪念馆, 古建筑, 文物保护, 文化活动, 竹林风光 ]
      沈园: [ 古典园林, 爱情故事, 传统建筑, 花卉展览, 文艺演出, 休闲游览 ]
      柯岩风景区: [ 自然风景区, 石灰岩溶洞, 古村落, 文物保护, 游船观光, 文化活动 ]
  江苏省:
    南京市:
      中山陵: [ 孙中山陵寝, 国家级风景名胜区, 文化遗产, 壮丽建筑, 游览步道, 花坛雕塑 ]
      夫子庙: [ 秦淮河畔, 文化街区, 历史建筑, 小吃美食, 夜景灯光, 文化活动 ]
      玄武湖: [ 城市公园, 湖泊风光, 游船观光, 休闲步道, 花卉展览, 水上活动 ]
      明孝陵: [ 世界文化遗产, 明朝皇陵, 古代建筑, 风景区, 历史文化, 游览观光 ]
      南京博物院: [ 国家级博物馆, 文物收藏, 历史展览, 文化教育, 临时展览, 互动体验 ]
    苏州市:
      拙政园: [ 世界文化遗产, 古典园林, 美丽风景, 传统建筑, 花卉展览, 文化活动 ]
      虎丘: [ 名胜古迹, 云岩寺塔, 剑池, 石刻艺术, 游览步道, 风景秀丽 ]
      寒山寺: [ 历史名寺, 唐代诗词, 古建筑, 佛教文化, 祈福圣地, 传统文化 ]
      平江路: [ 历史街区, 古桥古巷, 小吃美食, 手工艺品, 文化活动, 夜景灯光 ]
      留园: [ 世界文化遗产, 古典园林, 历史建筑, 花卉展览, 文化活动, 风景秀丽 ]
    无锡市:
      太湖: [ 中国五大淡水湖, 湖泊风光, 游船观光, 水上运动, 湖滨公园, 美食体验 ]
      灵山大佛: [ 佛教圣地, 巨型佛像, 佛教文化, 朝拜圣地, 风景区, 文化活动 ]
      鼋头渚: [ 太湖风景区, 樱花盛开, 湖泊美景, 游船观光, 历史文化, 休闲娱乐 ]
      惠山古镇: [ 历史街区, 传统建筑, 小吃美食, 手工艺品, 文化活动, 风景秀丽 ]
      无锡影视基地: [ 影视拍摄地, 古建筑群, 文化体验, 游览观光, 摄影佳地, 休闲娱乐 ]
    常州市:
      中华恐龙园: [ 主题公园, 恐龙文化, 游乐设施, 演出活动, 亲子游乐, 美食体验 ]
      天目湖: [ 湖泊风景, 游船观光, 水上运动, 生态保护, 美食体验, 休闲度假 ]
      淹城遗址: [ 历史遗址, 古城遗迹, 文化展览, 游览观光, 文化活动, 休闲娱乐 ]
      红梅公园: [ 城市公园, 花卉展览, 游船观光, 休闲步道, 文化活动, 儿童乐园 ]
      溧阳南山竹海: [ 自然风景区, 竹林美景, 休闲娱乐, 生态保护, 游览步道, 文化活动 ]
    扬州市:
      瘦西湖: [ 风景名胜区, 湖泊风光, 古桥古塔, 花卉展览, 游船观光, 文化活动 ]
      个园: [ 古典园林, 四季竹景, 传统建筑, 花卉展览, 文化活动, 风景秀丽 ]
      何园: [ 历史建筑, 古典园林, 花卉展览, 文化活动, 游览观光, 摄影佳地 ]
      大明寺: [ 历史名寺, 古建筑群, 佛教文化, 祈福圣地, 风景秀丽, 文化活动 ]
      扬州博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
  山东省:
    济南市:
      大明湖: [ 湖泊风光, 古桥古塔, 游船观光, 花卉展览, 历史文化, 休闲步道 ]
      趵突泉: [ 天下第一泉, 泉水观赏, 历史遗迹, 文化活动, 休闲娱乐, 风景秀丽 ]
      千佛山: [ 佛教圣地, 石刻佛像, 自然风光, 文化活动, 休闲登山, 花卉展览 ]
      五龙潭公园: [ 城市公园, 泉水风光, 游船观光, 文化活动, 休闲娱乐, 花卉展览 ]
      济南博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
    青岛市:
      栈桥: [ 海滨风光, 历史建筑, 游览观光, 海水浴场, 摄影佳地, 休闲娱乐 ]
      崂山: [ 道教圣地, 自然风景区, 登山步道, 文化活动, 花卉展览, 风景秀丽 ]
      八大关: [ 历史街区, 欧式建筑, 花卉展览, 文化活动, 摄影佳地, 休闲娱乐 ]
      五四广场: [ 城市广场, 标志性雕塑, 海滨风光, 文化活动, 休闲娱乐, 夜景灯光 ]
      青岛啤酒博物馆: [ 啤酒文化, 历史展览, 互动体验, 文化活动, 休闲娱乐, 美食体验 ]
    烟台市:
      烟台山: [ 风景名胜区, 历史建筑, 海滨风光, 文化活动, 游览观光, 休闲娱乐 ]
      蓬莱阁: [ 历史名胜, 仙境传说, 海滨风光, 文化活动, 休闲娱乐, 游览观光 ]
      张裕酒文化博物馆: [ 葡萄酒文化, 历史展览, 互动体验, 文化活动, 休闲娱乐, 美食体验 ]
      金沙滩: [ 海滨浴场, 沙滩娱乐, 海水观光, 休闲娱乐, 水上运动, 美食体验 ]
      南山公园: [ 城市公园, 自然风光, 花卉展览, 文化活动, 休闲步道, 儿童乐园 ]
    威海市:
      刘公岛: [ 历史名胜, 自然风景区, 海滨风光, 游船观光, 文化活动, 休闲娱乐 ]
      成山头: [ 自然风景区, 海滨风光, 日出观赏, 文化活动, 游览步道, 风景秀丽 ]
      威海国际海水浴场: [ 海滨浴场, 沙滩娱乐, 海水观光, 休闲娱乐, 水上运动, 美食体验 ]
      环翠楼公园: [ 城市公园, 历史建筑, 自然风光, 花卉展览, 文化活动, 休闲步道 ]
      华夏城景区: [ 主题公园, 历史文化, 休闲娱乐, 游览观光, 花卉展览, 文化活动 ]
    潍坊市:
      风筝博物馆: [ 风筝文化, 历史展览, 互动体验, 文化活动, 休闲娱乐, 风筝制作 ]
      十笏园: [ 古典园林, 传统建筑, 花卉展览, 文化活动, 游览观光, 摄影佳地 ]
      富华游乐园: [ 主题公园, 游乐设施, 休闲娱乐, 亲子游乐, 美食体验, 文化活动 ]
      白浪绿洲湿地公园: [ 湿地风光, 自然保护, 游船观光, 休闲步道, 花卉展览, 文化活动 ]
      潍坊世界风筝放飞场: [ 风筝活动, 国际赛事, 休闲娱乐, 文化活动, 游览观光, 摄影佳地 ]
  四川省:
    成都市:
      宽窄巷子: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 休闲娱乐, 夜景灯光 ]
      锦里古街: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 休闲娱乐, 手工艺品 ]
      青城山: [ 道教圣地, 自然风景区, 登山步道, 文化活动, 花卉展览, 风景秀丽 ]
      都江堰: [ 世界文化遗产, 水利工程, 游览观光, 文化活动, 休闲娱乐, 风景秀丽 ]
      武侯祠: [ 历史遗迹, 三国文化, 古建筑群, 文化活动, 游览观光, 摄影佳地 ]
    绵阳市:
      北川羌城旅游区: [ 羌族文化, 自然风光, 历史遗迹, 文化活动, 游览观光, 休闲娱乐 ]
      富乐山: [ 自然风景区, 登山步道, 花卉展览, 休闲娱乐, 文化活动, 游览观光 ]
      李白纪念馆: [ 历史遗迹, 文学文化, 纪念展览, 文化活动, 游览观光, 休闲娱乐 ]
      平武白马王朗景区: [ 自然保护区, 动植物观赏, 登山步道, 生态保护, 文化活动, 风景秀丽 ]
      江油窦圌山: [ 自然风景区, 登山步道, 花卉展览, 休闲娱乐, 文化活动, 游览观光 ]
    自贡市:
      自贡恐龙博物馆: [ 恐龙文化, 历史展览, 互动体验, 文化活动, 休闲娱乐, 科学教育 ]
      盐业历史博物馆: [ 盐业文化, 历史展览, 互动体验, 文化活动, 休闲娱乐, 教育活动 ]
      彩灯博物馆: [ 彩灯文化, 历史展览, 互动体验, 文化活动, 休闲娱乐, 灯展观赏 ]
      仙市古镇: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      恐龙遗址公园: [ 恐龙化石, 自然风景区, 互动体验, 游览观光, 文化活动, 科学教育 ]
    攀枝花市:
      攀枝花公园: [ 城市公园, 花卉展览, 游船观光, 文化活动, 休闲娱乐, 儿童乐园 ]
      米易太平古镇: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      二滩国家森林公园: [ 自然风景区, 森林保护, 游览步道, 休闲娱乐, 生态保护, 文化活动 ]
      阿署达花舞人间景区: [ 花卉展览, 自然风光, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      金江十八弯: [ 自然风景, 登山步道, 花卉展览, 游览观光, 文化活动, 摄影佳地 ]
    乐山市:
      乐山大佛: [ 世界文化遗产, 巨型佛像, 历史遗迹, 文化活动, 游览观光, 摄影佳地 ]
      峨眉山: [ 世界文化遗产, 佛教圣地, 自然风景区, 登山步道, 文化活动, 风景秀丽 ]
      乌尤寺: [ 历史名寺, 古建筑群, 佛教文化, 祈福圣地, 风景秀丽, 文化活动 ]
      嘉阳小火车: [ 怀旧火车, 自然风景, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      黑竹沟: [ 自然风景区, 登山步道, 花卉展览, 生态保护, 文化活动, 风景秀丽 ]
  福建省:
    福州市:
      三坊七巷: [ 历史街区, 传统建筑, 小吃美食, 民俗文化, 游览观光, 手工艺品 ]
      鼓山: [ 自然风景区, 登山步道, 花卉盛景, 文化活动, 休闲娱乐, 风景秀丽 ]
      福州西湖公园: [ 城市公园, 湖泊风光, 游船体验, 花卉展览, 休闲步道, 儿童乐园 ]
      永泰青云山: [ 自然风景区, 登山步道, 生态保护, 文化活动, 探险项目, 风景如画 ]
      福建博物院: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
    厦门市:
      鼓浪屿: [ 世界文化遗产, 海滨风光, 历史建筑, 音乐文化, 小吃美食, 休闲娱乐 ]
      南普陀寺: [ 佛教圣地, 古建筑群, 祈福圣地, 山水景观, 文化活动, 游览观光 ]
      厦门大学: [ 历史名校, 校园风光, 学术氛围, 文化活动, 休闲娱乐, 摄影佳地 ]
      环岛路: [ 海滨风光, 自行车道, 小吃美食, 文化活动, 休闲娱乐, 摄影热点 ]
      中山路步行街: [ 商业街区, 小吃美食, 购物天堂, 文化活动, 休闲娱乐, 夜景灯光 ]
    泉州市:
      清源山: [ 自然风景区, 登山步道, 花卉盛景, 文化活动, 休闲娱乐, 风景秀丽 ]
      开元寺: [ 历史名寺, 古建筑群, 佛教文化, 祈福圣地, 风景如画, 文化活动 ]
      崇武古城: [ 历史遗迹, 传统建筑, 海滨风光, 文化活动, 游览观光, 休闲娱乐 ]
      泉州博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      洛阳桥: [ 历史古桥, 工程奇迹, 海滨风光, 文化活动, 游览观光, 摄影佳地 ]
    漳州市:
      东山岛: [ 海滨风光, 沙滩娱乐, 海水观光, 休闲度假, 水上运动, 美食体验 ]
      南靖土楼: [ 世界文化遗产, 客家文化, 传统建筑, 游览观光, 文化活动, 摄影佳地 ]
      漳州火山岛: [ 自然风景区, 火山地貌, 海滨风光, 探险活动, 休闲娱乐, 摄影佳地 ]
      天宝岩国家森林公园: [ 自然保护区, 森林风光, 登山步道, 生态保护, 文化活动, 风景如画 ]
      漳州植物园: [ 植物展览, 自然风光, 生态保护, 游览步道, 文化活动, 休闲娱乐 ]
    龙岩市:
      永定土楼: [ 世界文化遗产, 客家文化, 传统建筑, 游览观光, 文化活动, 摄影佳地 ]
      龙岩石门湖: [ 自然风景区, 湖泊风光, 游船观光, 花卉盛景, 文化活动, 休闲娱乐 ]
      梅花山: [ 自然风景区, 花卉展览, 登山步道, 生态保护, 文化活动, 风景秀丽 ]
      龙岩博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      长汀古城: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
  湖南省:
    长沙市:
      岳麓山: [ 自然风景区, 历史遗迹, 登山步道, 文化活动, 风景秀丽, 休闲娱乐 ]
      橘子洲: [ 城市公园, 湖泊风光, 文学文化, 游船体验, 休闲娱乐, 花卉展览 ]
      马王堆汉墓: [ 历史遗迹, 考古发现, 文物展览, 文化活动, 游览观光, 教育意义 ]
      长沙博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      太平街: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
    张家界市:
      张家界国家森林公园: [ 自然风景区, 奇峰异石, 登山步道, 游览观光, 摄影佳地, 生态保护 ]
      天门山: [ 自然风景区, 登山步道, 天门洞, 玻璃栈道, 风景秀丽, 探险活动 ]
      黄龙洞: [ 喀斯特洞穴, 自然奇观, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
      宝峰湖: [ 自然湖泊, 山水风光, 游船体验, 文化活动, 休闲娱乐, 摄影佳地 ]
      袁家界: [ 自然风景区, 奇峰异石, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
    岳阳市:
      岳阳楼: [ 历史名楼, 文化遗迹, 湖泊风光, 文化活动, 游览观光, 摄影佳地 ]
      君山岛: [ 自然风景区, 湖泊风光, 登山步道, 文化活动, 休闲娱乐, 摄影佳地 ]
      洞庭湖: [ 自然湖泊, 水上观光, 生态保护, 游览观光, 文化活动, 摄影佳地 ]
      岳阳博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      黄盖湖湿地公园: [ 湿地保护区, 自然风光, 动植物观赏, 生态保护, 游览步道, 休闲娱乐 ]
    衡阳市:
      南岳衡山: [ 佛教圣地, 自然风景区, 登山步道, 文化活动, 风景秀丽, 休闲娱乐 ]
      衡阳南岳大庙: [ 历史名寺, 古建筑群, 佛教文化, 祈福圣地, 风景如画, 文化活动 ]
      石鼓书院: [ 历史遗迹, 传统建筑, 文学文化, 文化活动, 游览观光, 教育意义 ]
      蔡伦竹海: [ 自然风景区, 竹林风光, 游览步道, 文化活动, 休闲娱乐, 摄影佳地 ]
      衡阳博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
    常德市:
      桃花源: [ 自然风景区, 花卉盛景, 游览观光, 文化活动, 休闲娱乐, 风景如画 ]
      柳叶湖旅游度假区: [ 湖泊风光, 游船体验, 休闲娱乐, 水上运动, 美食体验, 摄影佳地 ]
      常德诗墙: [ 文学文化, 壁画艺术, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      城头山遗址: [ 历史遗迹, 考古发现, 文化展览, 教育活动, 游览观光, 互动体验 ]
      花岩溪森林公园: [ 自然风景区, 森林风光, 登山步道, 生态保护, 文化活动, 风景秀丽 ]
  湖北省:
    武汉市:
      黄鹤楼: [ 历史名楼, 文化遗迹, 长江风光, 文化活动, 游览观光, 摄影佳地 ]
      东湖风景区: [ 自然湖泊, 游船体验, 花卉展览, 休闲娱乐, 文化活动, 摄影佳地 ]
      湖北省博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      武汉大学: [ 历史名校, 校园风光, 樱花盛景, 学术氛围, 文化活动, 摄影佳地 ]
      归元寺: [ 佛教圣地, 古建筑群, 祈福圣地, 风景如画, 文化活动, 游览观光 ]
    黄石市:
      磁湖: [ 自然湖泊, 水上观光, 休闲娱乐, 文化活动, 摄影佳地, 生态保护 ]
      黄石国家矿山公园: [ 自然风景区, 矿山遗址, 游览观光, 文化活动, 摄影佳地, 互动体验 ]
      黄石博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      东方山: [ 自然风景区, 登山步道, 生态保护, 文化活动, 风景如画, 游览观光 ]
      黄荆山: [ 自然风景区, 登山步道, 花卉盛景, 生态保护, 文化活动, 风景秀丽 ]
    荆州市:
      荆州古城: [ 历史遗迹, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      张居正故居: [ 历史遗迹, 古建筑群, 文学文化, 游览观光, 文化活动, 摄影佳地 ]
      荆州博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      关公义园: [ 历史文化园区, 雕塑艺术, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      龙山风景区: [ 自然风景区, 登山步道, 生态保护, 文化活动, 风景如画, 游览观光 ]
    宜昌市:
      三峡大坝: [ 工程奇迹, 自然风光, 游览观光, 文化活动, 摄影佳地, 科普教育 ]
      三峡人家: [ 自然风景区, 民俗文化, 游览观光, 休闲娱乐, 文化活动, 摄影佳地 ]
      西陵峡: [ 自然风景区, 奇峰异石, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
      屈原故里: [ 历史遗迹, 文化展览, 游览观光, 教育活动, 文化活动, 互动体验 ]
      五峰山: [ 自然风景区, 登山步道, 花卉盛景, 生态保护, 文化活动, 风景秀丽 ]
    襄阳市:
      古隆中: [ 历史遗迹, 文化遗产, 游览观光, 休闲娱乐, 文化活动, 摄影佳地 ]
      襄阳城: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      襄阳博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      南漳春秋寨: [ 自然风景区, 登山步道, 文化遗迹, 生态保护, 游览观光, 摄影佳地 ]
      习家池: [ 自然风景区, 湖泊风光, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
  河北省:
    石家庄市:
      赵州桥: [ 历史古桥, 工程奇迹, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
      柏林禅寺: [ 佛教圣地, 古建筑群, 祈福圣地, 风景如画, 文化活动, 游览观光 ]
      石家庄博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      苍岩山: [ 自然风景区, 登山步道, 花卉盛景, 生态保护, 文化活动, 风景秀丽 ]
      正定古城: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
    唐山市:
      南湖公园: [ 城市公园, 湖泊风光, 游船体验, 花卉展览, 休闲娱乐, 文化活动 ]
      唐山抗震纪念碑: [ 历史遗迹, 文化纪念, 游览观光, 教育意义, 文化活动, 摄影佳地 ]
      开滦国家矿山公园: [ 自然风景区, 矿山遗址, 游览观光, 文化活动, 摄影佳地, 互动体验 ]
      唐山博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      迁安长城: [ 历史遗迹, 古建筑群, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
    秦皇岛市:
      山海关: [ 历史遗迹, 古建筑群, 长城风光, 文化活动, 游览观光, 摄影佳地 ]
      北戴河: [ 海滨风光, 沙滩娱乐, 海水观光, 休闲度假, 水上运动, 美食体验 ]
      老龙头: [ 历史遗迹, 古建筑群, 海滨风光, 文化活动, 游览观光, 摄影佳地 ]
      鸽子窝公园: [ 自然风景区, 海滨风光, 观鸟活动, 休闲娱乐, 摄影佳地, 风景如画 ]
      秦皇岛野生动物园: [ 野生动物保护区, 动物观赏, 自然风光, 文化活动, 互动体验, 生态保护 ]
    保定市:
      白洋淀: [ 自然湖泊, 水上观光, 生态保护, 游览观光, 文化活动, 摄影佳地 ]
      保定古莲花池: [ 历史园林, 花卉盛景, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      保定博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      直隶总督署: [ 历史遗迹, 古建筑群, 文学文化, 游览观光, 文化活动, 摄影佳地 ]
      狼牙山: [ 自然风景区, 登山步道, 奇峰异石, 生态保护, 文化活动, 风景秀丽 ]
    廊坊市:
      廊坊自然公园: [ 城市公园, 自然风光, 休闲娱乐, 游览观光, 花卉盛景, 摄影佳地 ]
      廊坊博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      大厂影视城: [ 影视拍摄基地, 文化活动, 游览观光, 休闲娱乐, 摄影佳地, 互动体验 ]
      固安梨园: [ 自然风景区, 梨花盛景, 生态保护, 文化活动, 游览观光, 休闲娱乐 ]
      香河县: [ 历史遗迹, 古建筑群, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
  安徽省:
    合肥市:
      包公园: [ 历史文化园区, 古建筑群, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      合肥滨湖湿地公园: [ 湿地保护区, 自然风光, 动植物观赏, 生态保护, 游览步道, 休闲娱乐 ]
      逍遥津公园: [ 城市公园, 游乐设施, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      三河古镇: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      合肥博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
    黄山市:
      黄山风景区: [ 自然风景区, 奇峰异石, 登山步道, 生态保护, 游览观光, 摄影佳地 ]
      宏村: [ 世界文化遗产, 传统建筑, 水乡风光, 游览观光, 文化活动, 摄影佳地 ]
      西递: [ 世界文化遗产, 传统建筑, 古村风光, 游览观光, 文化活动, 摄影佳地 ]
      屯溪老街: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      徽州古城: [ 历史遗迹, 传统建筑, 文学文化, 游览观光, 文化活动, 摄影佳地 ]
    蚌埠市:
      龙子湖: [ 自然湖泊, 水上观光, 生态保护, 游览观光, 文化活动, 摄影佳地 ]
      蚌埠博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      禹王庙: [ 历史遗迹, 古建筑群, 游览观光, 文化活动, 摄影佳地, 生态保护 ]
      淮河文化园: [ 文化园区, 文学文化, 游览观光, 文化活动, 休闲娱乐, 摄影佳地 ]
      蚌埠天河体育中心: [ 体育场馆, 运动设施, 休闲娱乐, 文化活动, 游览观光, 摄影佳地 ]
    芜湖市:
      芜湖方特欢乐世界: [ 主题乐园, 游乐设施, 文化活动, 休闲娱乐, 摄影佳地, 游览观光 ]
      鸠兹古镇: [ 历史街区, 传统建筑, 小吃美食, 文化活动, 游览观光, 休闲娱乐 ]
      芜湖镜湖公园: [ 城市公园, 湖泊风光, 游船体验, 花卉展览, 休闲娱乐, 文化活动 ]
      芜湖博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      芜湖大白鲸海洋公园: [ 海洋主题公园, 动物观赏, 互动体验, 文化活动, 休闲娱乐, 摄影佳地 ]
    安庆市:
      天柱山: [ 自然风景区, 奇峰异石, 登山步道, 生态保护, 游览观光, 摄影佳地 ]
      迎江寺: [ 佛教圣地, 古建筑群, 祈福圣地, 风景如画, 文化活动, 游览观光 ]
      安庆博物馆: [ 地方博物馆, 历史文物, 文化展览, 教育活动, 临时展览, 互动体验 ]
      桐城六尺巷: [ 历史街区, 传统建筑, 文学文化, 游览观光, 文化活动, 摄影佳地 ]
      小孤山: [ 自然风景区, 江河风光, 游览观光, 文化活动, 摄影佳地, 生态保护 ]

